name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build --no-cache -t vikolab/kraz-difyai-gb:latest .
          docker tag vikolab/kraz-difyai-gb:latest vikolab/kraz-difyai-gb:latest_commit_${{ github.event.head_commit.id }}
          docker push vikolab/kraz-difyai-gb:latest
          docker push vikolab/kraz-difyai-gb:latest_commit_${{ github.event.head_commit.id }}
        env:
          DOCKER_BUILDKIT: 1

  deploy-to-server:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Detener y eliminar el contenedor existente
            docker stop kraz_difyai_gb || true
            docker rm kraz_difyai_gb || true

            # Descargar la última imagen
            docker pull vikolab/kraz-difyai-gb:latest

            # Ejecutar el nuevo contenedor
            docker run -d --name kraz_difyai_gb \
              -p 8502:3000 \
              --env-file /home/viko/kraz-gbfoods/.env \
              vikolab/kraz-difyai-gb:latest \
              yarn start