name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: vikolab/kraz-difyai-gb:latest

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}  # IP del servidor
          username: ${{ secrets.SERVER_USERNAME }}  # Usuario SSH
          key: ${{ secrets.SERVER_SSH_KEY }}  # Clave privada SSH
          source: "deploy.sh"
          target: "/path/to/deploy.sh"  # Ruta en el servidor

      - name: Execute Deployment Script
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'bash /path/to/deploy.sh'