name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            vikolab/kraz-difyai-gb:latest
            vikolab/kraz-difyai-gb:latest_${{ format('{0:yyyy-MM-dd}', github.event.head_commit.timestamp) }}
          cache-from: type=registry,ref=vikolab/kraz-difyai-gb:latest
          cache-to: type=inline
          file: Dockerfile

  deploy-to-server:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Detener y eliminar el contenedor existente
            docker stop kraz_difyai_gb_test || true
            docker rm kraz_difyai_gb_test || true

            # Descargar la última imagen
            docker pull vikolab/kraz-difyai-gb:latest_${{ format('{0:yyyy-MM-dd}', github.event.head_commit.timestamp) }}

            # Ejecutar el nuevo contenedor
            docker run -d --name kraz_difyai_gb_test -p 8503:3000 --env-file /home/viko/kraz-gbfoods/.env vikolab/kraz-difyai-gb:latest_${{ format('{0:yyyy-MM-dd}', github.event.head_commit.timestamp) }}